name: Annie Lee-Zimerle
favicon: null
layout_spectrum: 0.90519
typography_spectrum: 0.8437
title: 'Annie Lee-Zimerle '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbe1ed'
    - '#3b2c2b'
    - '#dfbd75'
    - '#605e5c'
    - '#e87d4e'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
